sudo: required
language: python
python:
  - "2.7"
services:
  - docker
before_install:
    - sudo pip install docker-compose
install:
  - sudo pip install -r dev-requirements.txt
script:
    - sudo python tests.py
