sudo: required
language: python
python:
  - "2.7"
services:
  - docker
before_install:
    - sudo dpkg --purge docker
    - sudo dpkg --purge docker-engine
    - curl -sSL https://get.docker.com/ | sh
    - sudo pip install docker-compose
install:
  - sudo pip install -r dev-requirements.txt
script:
    - sudo python tests.py
